name: GitHub Metrics

on:
  # Programa la ejecución diaria a medianoche UTC
  schedule:
    - cron: '0 0 * * *'
  # Permite ejecutarlo manualmente desde la pestaña "Actions"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necesario para subir la imagen generada

    steps:
      - uses: actions/checkout@v4 # Clona el repositorio

      - name: Generar métricas
        uses: lowlighter/metrics@latest # Usa la acción de metrics
        with:
          # Tu token de GitHub. GITHUB_TOKEN es suficiente para la mayoría de los casos.
          # Para repositorios privados o datos más extensos, podrías necesitar un PAT.
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: metrics.svg # El nombre de archivo de salida
          user: Artur282 # ¡Tu nombre de usuario de GitHub!

          # --- Opciones generales y de base ---
          template: classic # Puedes probar otros templates como repository, terminal, markdown
          base: header, activity, community, repositories, metadata # Módulos base

          # --- Plugins para coincidir con tu README actual y añadir más ---

          # Similares a github-readme-stats (contribuciones y actividad general)
          plugin_isocalendar: yes # Muestra el calendario de commits (contribuciones)
          plugin_isocalendar_duration: full-year # Año completo
          plugin_languages: yes # Muestra los lenguajes más usados (similar a top-langs)
          plugin_languages_threshold: 0% # Incluye todos los lenguajes, no solo los significativos
          plugin_languages_skipped: css, html # Puedes omitir lenguajes si no quieres que aparezcan
          plugin_languages_indepth: yes # Análisis más profundo de lenguajes
          plugin_languages_details: bytes-size, percentage # Muestra tamaño y porcentaje
          plugin_languages_sections: most-used, recent-sources # Secciones de lenguajes

          # Para la "racha" (contribuciones continuas)
          plugin_streak: yes # Muestra la racha de contribuciones
          plugin_streak_sections: daily, weekly # Puedes elegir si mostrar daily, weekly o ambas

          # Otras características interesantes que puedes añadir:
          plugin_followup: yes # Muestra seguidores y siguiendo
          plugin_topics: yes # Muestra tus temas de repositorio principales
          plugin_topics_limit: 5 # Limita el número de temas mostrados
          plugin_repositories: yes # Muestra estadísticas de tus repositorios
          plugin_repositories_featured: Artur282/repository-name-1, Artur282/repository-name-2 # Opcional: Destaca repositorios específicos

          # Si quieres un diseño similar al "radical" de tus otras estadísticas,
          # puedes intentar ajustar los colores, pero esto es más avanzado.
          # style: dark # Prueba con 'dark' o 'light' para un tema general
          # colors:
          #   background: "#161b22" # Ejemplo de color de fondo oscuro (radical theme)
          #   text: "#c9d1d9"
          #   border: "#21262d"
          #   title: "#58a6ff"

          # Consulta la documentación oficial para más opciones:
          # https://github.com/lowlighter/metrics
